name: Update Scholarships Weekly

on:
  schedule:
    # Run every Sunday at 2 AM UTC (Saturday 9 PM EST)
    - cron: '0 2 * * 0'

  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  update-scholarships:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for proper commits

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scholarship updater
        run: |
          python scholarship_updater.py

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add scholarship_database.json
          git add update_report_*.txt
          git commit -m "Auto-update: Weekly scholarship refresh $(date +'%Y-%m-%d')" || exit 0
          git push

      - name: Create summary
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          echo "# 📚 Scholarship Database Updated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f update_report_*.txt ]; then
            echo "## Changes:" >> $GITHUB_STEP_SUMMARY
            cat update_report_*.txt >> $GITHUB_STEP_SUMMARY
          fi

      - name: No changes summary
        if: steps.check_changes.outputs.changes == 'false'
        run: |
          echo "# ✅ Scholarship Database Up to Date" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "No changes were needed for this week's update." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Checked:** $(date)" >> $GITHUB_STEP_SUMMARY
